### ISSUE TITLE
Could this be made into a template?

### ISSUE THREAD

**Issue by nickchomey** [ConduitIO/conduit-processor-example#23]
The connectors have a template repo which along with the `setup.sh` script, makes it easier to create our own connector repo.

Could/should something like that be done here?

**Comment by hariso** [comment]
@nickchomey we actually got that done, pretty recently: https://github.com/ConduitIO/conduit-processor-template

**Comment by hariso** [comment]
Yup, yup, you're right.:) That page is in the making, we have an open PR for that.:)
